### ISSUE TITLE
Falla en Visible Absorptance y falla en encabezados

### ISSUE THREAD

**Issue by gabyagaa** [AltamarMx/osm_handler#2]
La Visible Absorptance =0.7 en todos los materiales aunque en el osm tenga otra. En los encabezados del .json al abrirlo con Jupyter Lab quedan los handlers y no el nombre del material como en la versión pasada.

**Comment by eapuertoc** [comment]
Saludos.
El error de la absortancia visible estaba en la función ___create_dictionary_, tenía un for que excluía el último ítem. Asumo que porque este último no se separaba por ',' sino por ';', lo que no entiendo es como el commit previo funciona si tiene la misma función. Lo checaré luego. Sobre lo de los encabezados, el argumento "use_handle" define si se utiliza o no el handle como encabezado, la libreta tenía el argumento como TRUE, ya lo eliminé, ya que por defecto utiliza el FALSE. Esto era jústamente para ver si se podía cambiar nombres de los materiales y actualizar por handle.
